### ISSUE TITLE
Viewing scheduled posts gives "NULL at path $[0].params.sensitive"

### ISSUE THREAD

**Issue by austinhuang0131** [pachli/pachli-android#1057]
**Describe the bug**
When viewing scheduled posts, the error is given as

> Your server returned an invalid response: Expected a boolean but was NULL at path $[0].params.sensitive

I did check the output from Mastodon API and indeed `params.sensitive` for each post is set to `null`, so I think the app should handle it.

**To Reproduce**
1. I used https://seleb.github.io/mastodon-post-scheduler/ to make scheduled posts. I can confirm that my Mastodon instance (which is vanilla) does send them out.
2. Go to Pachli and view scheduled posts

**Expected behavior**
Show scheduled posts.

**Screenshots or video**

**Links**
The API output for 1 post:

```json
{
        "id": "12345",
        "scheduled_at": "2024-10-29T12:00:00.000Z",
        "params": {
            "poll": null,
            "text": "sample text",
            "language": null,
            "media_ids": null,
            "sensitive": null,
            "visibility": "public",
            "idempotency": null,
            "scheduled_at": null,
            "spoiler_text": "",
            "application_id": 12345,
            "in_reply_to_id": 12345,
            "with_rate_limit": false,
            "allowed_mentions": null
        },
        "media_attachments": []
}
```

**Versions**
Pachli 2.8.2
Android 14 (SDK 34)
Mastodon 4.2.13

**Additional context**

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report. I'll have a fix for this shortly and it will be in the next release.
