### ISSUE TITLE
Crashing on severed relationships notification

### ISSUE THREAD

**Issue by sqrtiswap** [pachli/pachli-android#1086]
**Describe the bug**

Pachli crashes on the notification tab after I severed a relationship during a domain block and got a notification (see below) for it.
The notification in the web ui looks like this:
![severed_notification](https://github.com/user-attachments/assets/810a0e50-035a-455c-aa63-a0ae8a0233d1)
Previous notifications are briefly visible in Pachli before the crash.

When disabling `Severed relationships` in the notifications filter the crash doesn't happen and the other notifications are displayed as expected. Upon reenabling the display of severed relationships the crashing resumes.

**To Reproduce**
1. Block a domain that a follow (presumably follower works as well) is using resulting in a severed relationship.
2. Open the notification tab in Pachli.
3. Upon trying to load the notifications Pachli crashes.

**Expected behavior**
Either display the notification or if that is not supported at least don't crash.

**Versions**
Device: Google Pixel 6
Android version: 15 (GrapheneOS 2024110700)
Pachli version: 2.8.3 (fdroid build)
Server: exquisite.social, version 4.4.0-EXQ1.31+glitch

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, sorry about that. By any chance, would it be possible for you to get the JSON representation of the notification from the API (e.g., from your browser's dev tools "Network" tab) and paste it here (redacting e.g., the name of the domain that was blocked). That'll make troubleshooting this a little easier.

**Comment by sqrtiswap** [comment]
Hi, networking is not really within my area of expertise, so apologies if this is not what you were asking for. But this looked most relevant to me:

```json
{
    "group_key": "ungrouped-67649",
    "notifications_count": 1,
    "type": "severed_relationships",
    "most_recent_notification_id": 67649,
    "page_min_id": "67649",
    "page_max_id": "67649",
    "latest_page_notification_at": "2024-11-09T22:53:39.910Z",
    "sample_account_ids": [
        "112657188779128444"
    ],
    "event": {
        "id": "11",
        "type": "user_domain_block",
        "purged": false,
        "target_name": "supersecretandblockedmastodonserver",
        "followers_count": 0,
        "following_count": 1,
        "created_at": "2024-11-09T22:53:39.202Z"
    }
}
```

If this is indeed not what you meant, please let me know and I'll have another look.

**Comment by nikclayton** [comment]
Thanks, that helped. I've found and fixed the problem, and the fix will be in the Pachli release at the end of the month.

**Comment by sqrtiswap** [comment]
Awesome, thanks!
