### ISSUE TITLE
[BUG] Pachli and SSO / OIDC with authentik and webauthn as 2FA

### ISSUE THREAD

**Issue by Morethanevil** [pachli/pachli-android#1091]
**Describe the bug**
I use SSO on Mastodon and wanted to test it with Pachli. I enforce 2FA in authentik via webauthn (Yubikey, passkey)
Pachli opens my sign in website from authentik, but it refuses to load the prompt from android for webauthn. Instead, Pachli simply tells me my browser would not support it. I have Firefox and Brave as browser, both have no problems with webauthn and I can log in without issues.

**To Reproduce**
1. Try sign in via SSO
2. Choose webauthn as 2FA (I used a Yubikey)
3. See error

**Expected behavior**
After successful password prompt, Pachli should load the webauthn prompt 

**Screenshots or video**
n.a

**Links**
n.a

**Versions**

Latest from Playstore 2.8.3
Android 14
Oneplus 9 Pro (LE2123)
Mastodon 4.3.1

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

Found no existing or closed issues for SSO or OIDC

**Comment by nikclayton** [comment]
Does it work if, on the login screen you:

1. Enter the server name as normal
2. Instead of clicking the "Login with Pachli" button, use the three-dot menu at the top right and choose "Login with Browser"

?

**Comment by Morethanevil** [comment]
Yes this works, the browser can login without ptoblems and I only need to authorize Pachli.
