### ISSUE TITLE
Mentions, links, and hashtagsno longer work when using accessibility actions

### ISSUE THREAD

**Issue by BlindMoon38** [pachli/pachli-android#1108]
**Describe the bug**

When viewing links, hashtags, or mentions using accessibility actions with TalkBack,  selecting an item from the list no longer navigates to its destination, the app appears to do nothing.

**To Reproduce**
1. Go to the toot linked below using Pachli with TalkBack enabled.
2. Use Accessibility actions to see the mention in the toot.
3. Try to activate the username, so the app navigates to the profile of the user being mentioned.
4. The app appears to do nothing. This behaviour occurs when seeing links and hashtags, as well.

**Expected behavior**
The app should navigate to the destination of a mention, link, or hashtag when using accessibility actions.

**Screenshots or video**
If applicable, please add screenshots or video to help explain your problem.

**Links**
https://dragonscave.space/@BlindMoon38/113407077243503352

**Versions**
Pachli 2.8.3.
Device:

Xiaomi Poco X6 5G.
Android: 14 (HyperOS 1.0.15.0).
SDK: 34.
TalkBack: 15.0.

Account:

@BlindMoon38@dragonscave.space 
Versión: 4.4.0-alpha.1+glitch

**Additional context**

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, sorry about that. I can reproduce this on some systems, I'll have a fix soon.
