### ISSUE TITLE
Add Norwegian Nynorsk option in language selection menu

### ISSUE THREAD

**Issue by turtlegarden** [pachli/pachli-android#1159]
**Feature request**
Since my translation of Pachli to Norwegian Nynorsk is now done, I think it would be nice to have an option to select the language inside the app and not just through system settings (on newer Android versions). 

**Additional context**
(To be specific, I mean the menu inside the *Settings* page where one can choose the app language.)

**Comment by nikclayton** [comment]
Good idea. That'll be in the next Pachli Current, releasing later today.
