### ISSUE TITLE
Media thumbnails loading options ("ask", "always" and maybe "wifi")

### ISSUE THREAD

**Issue by tzeumer** [pachli/pachli-android#1163]
**Is your feature request related to a problem? Please describe.**
Attachments (pictures & videos) often take up a lot of space on the timeline. In most cases I am more interested in the text than the images. Also, images are often very bright, which ruins the "dark mode experience" when it is active. 

**Describe the solution you'd like**
A setting like "Media thumbnail loading behavior" with the options "ask" and "always" (and maybe "on wifi"). If "ask" is selected, a button like "Show/Load Media" will appear in the post instead of the media.

**Comment by nikclayton** [comment]
You already have most of this in the "Account preferences > Download media previews" option.

If you turn that off then the media is not downloaded, and the caption is shown instead.

You can still tap the caption to load the media.

**Comment by tzeumer** [comment]
Sorry for opening this ticket. I checked triple but still missed the option. I guess I expected it to be in the preferences. Anyway, your alt text solution is even better. 

Thanks for the quick response. I will close the ticket.
