### ISSUE TITLE
Sync with Weblate more often

### ISSUE THREAD

**Issue by turtlegarden** [pachli/pachli-android#1167]
### Is your feature request related to a problem? Please describe.
I maintain the Norwegian Bokmål and Nynorsk translations for Pachli, and every time a new release comes out, all of the new strings are not translated, as I could not translate them before the release.

### Describe the solution you'd like
I would like it if the translation files were updated during the time between releases as well, such that translators would get a chance to translate new strings before the release.

### Additional context
This does not nessescarily mean syncing *from* Weblate often, just updating translation files every so often that Weblate's strings can be up to date and the strings can be translated before the release.

**Comment by nikclayton** [comment]
Hi -- first, thanks for all the translation work, it's appreciated.

I'm not quite sure what you're asking for here, so to check / go through the current process.

1. When I create a new English string or modify an existing one that change should show up in Weblate a few seconds to a few minutes after the change is submitted via GitHub, assuming there are no problems at Weblate.

2. When you or other translators make changes in Weblate they get pushed to GitHub every ~ 24 hours, either to an existing PR (if it exists) or creating a new one.

3. As part of the release process I check to see if there are any pending changes at Weblate, and if there are I trigger a push from Weblate to create a PR with the changes, which I review and then rebase in GitHub.

It sounds like you're saying that step 1 is not working as expected -- you see a change to an English string (or a new English string) in GitHub, and that change is not available in Weblate within a few minutes. Is that right?

**Comment by turtlegarden** [comment]
It could be *just* for the few languages I translate to, though.

**Comment by nikclayton** [comment]
There do seem to have been some delays between Weblate and GitHub.

I've just looked at one -- https://github.com/pachli/pachli-android/commit/57be148fbf64b67881fb2769d9c872b75c59b764#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103. This added some new strings to `values/strings.xml`.

This was at 2024-12-03T22:00:31.000Z

If I look at the history for this in Weblate (https://hosted.weblate.org/projects/pachli/app-main/, then "Insights > History") and scroll back multiple pages (at the time of writing, 24) to https://hosted.weblate.org/changes/browse/pachli/app-main/?page=24&limit=20 I can see that Weblate picked that up at 2024-12-06T12:36:25+00:00, about two and a half days after the initial commit.

It's not immediately clear what the cause of the delay was.

However...

Right now, if I look at the "Info" section for the same Weblate component, https://hosted.weblate.org/projects/pachli/app-main/#information, I can see it's up to date with the most recent change in the repository, which was about 3 hours ago.

I've got a pending PR to commit, so I'll commit that, and time roughly how long it takes for that commit to show up in the Weblate UI...

... OK, done that. It took ~ 10 seconds from me hitting the "Squash" button in GitHub to seeing the commit show up in https://hosted.weblate.org/projects/pachli/app-main/#information. That's about what I would expect.

So it might just be some recent slowness that's been resolved now.

If you see this happen again I think the best thing to do would be if you could:

1. Get the most recent GitHub commit from https://github.com/pachli/pachli-android/commits/main/
2. Compare this with the "Last remote commit" entry on https://hosted.weblate.org/projects/pachli/app-main/#information
3. If Weblate appears to be behind by more than a few minutes report this at https://github.com/WeblateOrg/weblate/issues/new/choose so the Weblate team can investigate further. They'll have the necessary access to be able to diagnose this in more detail

**Comment by turtlegarden** [comment]
Thanks!

**Comment by turtlegarden** [comment]
I'll close this now
