### ISSUE TITLE
Connection line missing in conversation threads

### ISSUE THREAD

**Issue by vinzv** [pachli/pachli-android#148]
**Describe the bug**
Compared to Tusky the connection line between to in-thread posts is missing. This is slightly unfortunate as you loose context while scrolling.

**To Reproduce**
1. Go to a conversation
2. Take a look on the left side

**Expected behavior**
If it was on purpose, could you re-add this line? 

**Screenshots or video**
Pachli:\
![grafik](https://github.com/pachli/pachli-android/assets/74432/824b50d2-4869-479a-9ea2-a948230c9c7a)

Tusky:\
![grafik](https://github.com/pachli/pachli-android/assets/74432/7dbae9ac-c20d-4ac4-b3d4-06aa401c9de2)

**Versions**
Pachli 1.2.2

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Huh, not deliberate, that's a bug. Thanks for the report.

**Comment by s-hgr** [comment]
This is the case with the dark and the light theme. In the black theme the lines are there.
