### ISSUE TITLE
Timeline gaps after absence

### ISSUE THREAD

**Issue by nikclayton** [pachli/pachli-android#16]
**Describe the bug**

Returning and reload a cached timeline shows gaps in the timeline

**To Reproduce**

1. Open home timeline
2. Leave the app for enough time that more than a page size of new posts have been posted
3. Refresh
4. Some posts are missing

**Expected behavior**

No posts should be missing.

**Links**

https://mastodon.world/@JoeP/111033819630407538

**Versions**

Pachli 1.0

**Comment by langhaarschneider** [comment]
Sadly I have to confirm this bug.
