### ISSUE TITLE
Fullscreen image is not shown when moving back to app

### ISSUE THREAD

**Issue by fourlastor** [pachli/pachli-android#161]
**Describe the bug**
When switching back to Pachli from another app, while an image within a post is opened, the image isn't shown 

**To Reproduce**
1. Go to the post linked below
2. Click on the image so it goes fullscreen 
3. Switch to a different app without closing the maximised image
4. Go back to Pachli
5. The image isn't shown anymore

**Expected behavior**
The image should be shown upon resuming the app

**Screenshots or video**
![Screenshot_20231014-091826](https://github.com/pachli/pachli-android/assets/1263058/47ee60df-f050-44c5-b49e-e7996d945dee)
![Screenshot_20231014-091834](https://github.com/pachli/pachli-android/assets/1263058/6abf21fb-7ccb-47a4-8254-e0ed35df2bde)

**Links**
https://livellosegreto.it/@sio/111232083593406897 

**Versions**
Pachli: 1.2.2
Android: 12 (pixel 3a latest update) 

**Additional context**
The post loads correctly when closing the full screen image and reopening it

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, and the reproduction steps. I can reproduce this, so hopefully the fix will be straightforward.
