### ISSUE TITLE
Pachli current crashes when I make a post

### ISSUE THREAD

**Issue by nrgeen** [pachli/pachli-android#162]
I have just created a post and was about to send it. When I clicked on "Toot", the app disappeared from the screen and virtually closed. When I reopened it, there was no indication of the post. It has disappeared.

**To Reproduce**
1. Go to 'new Post'
2. Create a new Post
3. Click on t'oot'
4. App disapear

**Expected behavior**
The Post should appear in the timeline

**Screenshots or video**

**Versions**
Pachli Current 1.2.2+ca06d46d

Device:

Google Pixel 6 
Android-Version: 14 
SDK-Version: 34

Account:

@alex@libori.social 
Version: 4.2.1

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nrgeen** [comment]
Hmm... I guess the video thing didn't work. Here is a link:
https://zuhause.mueller-post.de/s/H4MdKwoTJr8mKY2

**Comment by nikclayton** [comment]
Hi, thanks for the report and the video. I've got a couple of questions:

1. Was this a one-off, or does it happen every time you try and post?
2. Does it also happen with not-Pachli-current (i.e., version 1.2.2, blue icon)?

Thanks

**Comment by nrgeen** [comment]
Hey. For sure. 👍

Unfortunately, I can't post anything with Pachli current. Both with media and without. I have also tried different visibility settings. The app crashes every time.
The problem does not occur in the current "stable" version. I can post there without any problems.

Thank you for your effort!

**Comment by nikclayton** [comment]
Thanks. I can reproduce the problem now, which should make fixing it simpler.

And thanks for trying Pachli Current, these are the sorts of issues it's supposed to uncover.

**Comment by nikclayton** [comment]
A new version of Pachli Current with the fix has been published, and it's waiting for Google to review (normally takes 6-12 hours).

The release with the fix will identify as version 1.2.2+99dd15ea.

**Comment by nrgeen** [comment]
Thank you very much! I am looking forward to it. 😁
