### ISSUE TITLE
Pachli Current: use orange app icon for notifications to match app icon color

### ISSUE THREAD

**Issue by foss-** [pachli/pachli-android#178]
Currently the notifications icon is blue for pachli and green for pachli current.

**Expected**
This is slightly confusing. Matching application icon colors would be more consistent:
- blue for pachli
- orange for pachli current

<img src="https://github.com/pachli/pachli-android/assets/5708172/16e14e63-167d-4cb0-99a4-a7f151e2f876" width="450">

**Comment by nikclayton** [comment]
Good point. Thanks for the report.

**Comment by foss-** [comment]
Looks lovely in Pachli Current 🧡
