### ISSUE TITLE
Replying to a post shouldn't advance your timeline position to now

### ISSUE THREAD

**Issue by caoilte** [pachli/pachli-android#185]
When I'm catching up on my timeline I sometimes want to reply to other peoples posts. If I do so, the post process then immediately advances my timeline so that it can show my post in context of where it appears in the timeline (ie the latest post).

This is frustrating because I either lose my place and have to scroll back to find where I was reading my timeline or learn not to reply and do so later as a separate operation. 

It would be better if replying to a post didn't change your position in the timeline at all. Or possibly just showed the thread that it was now a part of without advancing your position in the timeline. I imagine the code surrounding this "feature" is gnarly and don't hold out much hope that it can be fixed quickly or easily but I thought I'd drop a place marker for it as I've been really impressed by the other fixes that have gone into this app.

**Comment by nikclayton** [comment]
Which version? I just did a reply to a post that was from two days ago (in Current) and the reading position wasn't reset, it stayed at the post I was replying to.

Can you catch this behaviour on video?

**Comment by caoilte** [comment]
Grrr. It happened when I had nearly a week to catchup on in the timeline. When I only had a half a day or so it didn't happen. Maybe the longer timeline to catchup was a factor (eg multiple API calls required to fill it) or maybe there were other factors I'm unaware of at work. 

I'm going to close it for the moment. Will reopen if I ever manage to reproduce.

**Comment by nikclayton** [comment]
> It happened when I had nearly a week to catchup on in the timeline.

Hmm. Any chance you had a large number of posts above your reading position?

When you send or edit a post (doesn't matter if it's a reply or not) your timeline is refreshed to get up-to-date content around your reading position (https://github.com/pachli/pachli-android/blob/566b23ed0684db736e22183b84ea9fd582a6f4f0/app/src/main/java/app/pachli/components/timeline/TimelineFragment.kt#L664-L691).

But your Mastodon server doesn't keep your timeline indefinitely. Typically it'll only keep the most recent 800 (used to be 400) posts on your home timeline.

So if you had more than 800 (or maybe 400, depending on your server) newer posts in the timeline above your reading position then your reading position technically no longer exists on the server, and can't be restored.

One way to prove/disprove this theory is this -- when this happened to you, were you able to scroll back through a week's worth of posts and get back to your original reading position (I appreciate you may not have bothered to do this, it would have been a lot of scrolling).

If you did do this and you got back to your previous reading position then my hypothesis above is wrong and something else is going on. But if you did try this and you couldn't get back then the hypothesis is right.
