### ISSUE TITLE
Image aspect ratio is not maintained when dragging it

### ISSUE THREAD

**Issue by fourlastor** [pachli/pachli-android#202]
**Describe the bug**
When dragging an image in fullscreen, the image aspect ratio changes upon releasing it. This is a very minor bug but I thought it was worth reporting.

**To Reproduce**
1. Go to a post with an image (see link for example)
2. Open the image in fullscreen
3. Note the image has the correct aspect ratio
4. Drag the image around a bit and release it
5. The image has a different aspect ratio than before

**Expected behavior**
The image returns to the correct aspect ratio upon being released

**Screenshots or video**

https://github.com/pachli/pachli-android/assets/1263058/3fea36ba-71c1-4051-b8d0-62cc5cff307f

**Links**

https://androiddev.social/@fourlastor/111301426974799595

**Versions**
Google Pixel 3a
Android 12
Pachli 1.3.0

**Additional context**
N/A

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the detailed report. Should be a straightforward fix.

**Comment by fourlastor** [comment]
Thanks for all the quick fixes! 🙏🏻
