### ISSUE TITLE
White buttons on white background for system buttons bar on older Androids

### ISSUE THREAD

**Issue by Porkepix** [pachli/pachli-android#221]
**Describe the bug**
On older versions of Android if the theme is light or during loading of the application, system bar buttons appears white over white background, making them difficult to read. This also happens on the login screen.

**To Reproduce**
Just use the application in light theme on old Android

**Expected behavior**
This should be white on white.

**Screenshots or video**

<details>
<summary>
Screenshot
</summary>

![Screenshot_20231105-174045](https://github.com/pachli/pachli-android/assets/709500/5420e84d-522a-4553-96a6-1daaf9b8c9e9)

</details>

**Versions**
Latest release from F-droid (1.2.2) on Android Oreo (8.0), stock build

**Additional context**
For reference, similar fixed issues:
https://github.com/Mosc/Glider/issues/123
https://github.com/Livinglist/Hacki/issues/184
https://github.com/beemdevelopment/Aegis/issues/531
https://github.com/celzero/rethink-app/issues/802

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, and for the relevant links, that was very helpful. This will be fixed in the next release.
