### ISSUE TITLE
Caption text in audio files is hard to read

### ISSUE THREAD

**Issue by sanao1006** [pachli/pachli-android#243]
**Describe the bug**
When trying to set a caption for an audio file, the text entered is unreadable due to the low height of the text entry area.
Also, can't read the hints displayed before entering text.

**To Reproduce**
1. Press create toot button.
2. Tap "Add media" to attach an audio file
3. Tap "Set caption

**Screenshots or video**
<image src="https://github.com/pachli/pachli-android/assets/62137820/997f3af1-ee71-447c-ab51-4b4db9c47b9d" width="300" />

**Expected behavior**
Maybe the text input area should be slightly expanded as shown in the image.
<image src="https://github.com/pachli/pachli-android/assets/62137820/be91c419-3721-43c9-bed4-bb23c4436252" width="300" />

**Versions**
Device: Google Pixel6a
Android version: 14
SDK level: 34
server: mastodon.social Mastodon v4.2.1

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by Jasdemi** [comment]
I'm also having the same issue. 
Pachli 2.7.1

Device:

Google Pixel 6a
Android version: 14
SDK level: 34

Account:

@jasdemi@jasdemi.com
Version: 0.16.1-SNAPSHOT+git-889d475

![Screenshot_20240820-201336](https://github.com/user-attachments/assets/9749d4a4-c3f8-4601-b85f-cb5e6776c35a)
