### ISSUE TITLE
Pachli Current: App immediately crashes on startup

### ISSUE THREAD

**Issue by bakaminto** [pachli/pachli-android#250]
**Describe the bug**
Launching the app results in immediate crash and close.
Deleting all app data results in the app starting and asking for login to a server, but right after successful login (in my case to mastodon.social) the app crashes again.
complete uninstall/reinstall makes no difference.

**Versions**
1.4.0+d40b87f0
 
Android 14
Pixel 7a

**Additional context**
As the app closes immediately there is not much else to describe/provide unfortunately.
it started happening after today's update.
pachli stable (1.4.0) works fine.

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by s-hgr** [comment]
Same behaviour for me. Immediate crash without opening at all. 

Pixel 8 Pro
Android 14
UD1A.231105.004

**Comment by nikclayton** [comment]
Thanks both for the notification. Investigating this now.

**Comment by dnkrupinski** [comment]
I can confirm this behaviour on Nokia G50 (Android 13) and Fairphone 4 (Android 13). 

Starts and crashs immediatly. 

Very rare i can see the regular screen in background with error message from system on top.

**Comment by nikclayton** [comment]
The new version is showing in Google Play already.
