### ISSUE TITLE
Replace androidx.appcompat.widget.Toolbar with com.google.android.material.appbar.MaterialToolbar

### ISSUE THREAD

**Issue by nikclayton** [pachli/pachli-android#28]
Many of the layouts still use `androidx.appcompat.widget.Toolbar` as the toolbar.

They can be updated to use `com.google.android.material.appbar.MaterialToolbar` instead.

This should (generally) be a search and replace, but the screens should be checked to ensure there is no unexpected behaviour changes.

The documentation for the widget is at https://github.com/material-components/material-components-android/blob/master/docs/components/TopAppBar.md.

https://github.com/pachli/pachli-android/commit/ecd81e80b0a2e303ad6ce98067916c63f992b5b5 changed this for some layouts, and can be used for inspiration.

**Comment by sanao1006** [comment]
I would like to work on this task!

**Comment by nikclayton** [comment]
Thanks. This might be a little more involved though.

I'd like to avoid doing this as a one-off, and then hoping that future uses of `androidx.appcompat.widget.Toolbar` don't creep back in to the code. That's the sort of thing that's easy to miss in a code review.

We can create custom `lint` rules that check this instead. That way the problem will be detected when `gradlew lint` is run, and the problem will also appear as a warning in Android Studio and it can be corrected there.

So the first part of solving this would be writing the new lint rule, and verifying it finds all the problems. And the second part would be fixing those problems, knowing that they can't reoccur.

If you've not written custom lint rules before here are some PRs and code to look at:

https://github.com/tuskyapp/Tusky/pull/3673/files was for adding lint checks for the design system. I'm going to bring that in to Pachli at some point (but screenshot tests are necessary for that). But it does show the things you need to. Roughly:

1. Create a new project to contain the checks. The PR calls that `checks`, and adds it to `app/build.gradle` and `settings.gradle`.
2. Create the project machinery in the `checks` directory (`build.gradle`, the `checks/src` tree, `LintRegistry.kt`)
3. Actually write the lint rule (`RawDimensionDetector.kt` and tests).

`RawDimensionDetector` isn't going to great as an example because it's looking at resource use. But https://github.com/vanniktech/lint-rules/blob/master/lint-rules-android-lint/src/main/kotlin/com/vanniktech/lintrules/android/AlertDialogUsageDetector.kt is a good example. That looks for usage of `android.app.AlertDialog` and raises an issue.

The lint here would be similar, except it would be looking for `androidx.appcompat.widget.Toolbar`.

Does that make sense? Is that something you're comfortable attempting?

**Comment by sanao1006** [comment]
Hmmm, I thought it was just an issue to simply replace, but it sure seems complicated.

I have no experience in creating custom lint rules.
But if I can solve this issue it would be a good experience for me, so I want to try!

If I decide it's not possible, I'll get back to you from here as soon as possible.

**Comment by nikclayton** [comment]
Sounds good. I found writing a lint rule an interesting learning experience, and it's one of those things where when you've done it once you start seeing many other issues that can be fixed the same way.

If you get stuck with something please feel free to create a PR, even if the code doesn't work, I can help with the debugging.

**Comment by sanao1006** [comment]
I am still working on this task. 

Please let me work on this task for a couple more days.  I will create a PR by the end of this week, whether it's done or not.

**Comment by nikclayton** [comment]
No problem at all.
