### ISSUE TITLE
Add scheduled time in shceduled posts view

### ISSUE THREAD

**Issue by lgasp** [pachli/pachli-android#293]
**Is your feature request related to a problem? Please describe.**
When I have more than one scheduled post, it is tedious to see for which time each is scheduled

**Describe the solution you'd like**
In the scheduled posts view, I would like to see the scheduled time in each post item, without having to open them

**Describe alternatives you've considered**
Fedilab implement this, a view of all scheduled posts, where the scheduled time is shown under each post. Fedilab doesn't allow you edit the posts, tho

**Additional context**

Pachli scheduled post view:
![pachli scheduled post view](https://github.com/pachli/pachli-android/assets/3661279/fda8de86-f437-4881-b303-11e04dc0ee05)

Fedilab scheduled posts view as reference:
![fedilab view](https://github.com/pachli/pachli-android/assets/3661279/60a9fa35-e567-4b80-84ec-7285a8114b62)

**Comment by nikclayton** [comment]
Good idea, thanks. I've got plans to revamp the scheduled view to show more useful information, I'll make sure this is included.

**Comment by lgasp** [comment]
@nikclayton thank you, it works great!

Keep up the good work!
