### ISSUE TITLE
Add screenshot with black color theme to F-Droid

### ISSUE THREAD

**Issue by Korb** [pachli/pachli-android#304]
Currently, [the app page on F-Droid](https://f-droid.org/packages/app.pachli/) only shows screenshots of the light color theme.  This may make it appear that this app does not support themes for AMOLED screens.

**Comment by nikclayton** [comment]
Good idea. I'll prepare an updated set.

**Comment by nikclayton** [comment]
@Korb New screenshots have been uploaded. I'm not sure if F-Droid will pick them automatically, or if I'll need to roll a new release first that includes them. Thanks for the suggestion.
