### ISSUE TITLE
Pachli 2.1.0 crashes after upgrade with "Trending posts" tab

### ISSUE THREAD

**Issue by raimue** [pachli/pachli-android#329]
**Describe the bug**
I upgraded to Pachli 2.1.0 from the Google Play Store. Whenever I tap the app icon, the splash screen appears shortly but then the app closes.

I was able to extract the following log messages with `adb logcat`:
```
12-17 02:41:40.729  9963  9963 E AndroidRuntime: Process: app.pachli, PID: 9963
12-17 02:41:40.729  9963  9963 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.pachli/app.pachli.SplashActivity}: java.lang.IllegalArgumentException: No enum constant z6.n.TRENDINGSTATUSES
12-17 02:41:40.729  9963  9963 E AndroidRuntime: 	at app.pachli.SplashActivity.onCreate(SourceFile:21)
```

Please let me know if there would be anything else I could extract to provide more information about this crash.

**To Reproduce**
1. Launch app

**Expected behavior**
Pachli opens.

**Versions**
Please include the version of Pachli and Android you are using, and the software version your server is using. Find this on the Pachli "About" screen.

* Pachli 2.1.0 (Google Play Store)
* OnePlus Nord 2T 5G
* Android 13 (patch level November 5, 2023)

**Comment by raimue** [comment]
Based on the "TRENDINGSTATUSES" from the stack trace, I was able to track this down to the "Trending posts" in the tabs.

1. Downgrade to Pachli 2.0.0 apk (which still works fine)
2. Remove the "Trending posts" from the tabs
3. Upgrade to Pachli 2.1.0
4. Pachli launches as expected

I assume the crash occurs when incompatible serialized data from the old version is being loaded.  This is most probably related to the fix for #306.

**Comment by nikclayton** [comment]
Yes. Thanks for the detailed report. I've paused the 2.1.0 rollout and am prepping 2.1.1 with the fix now.

**Comment by raimue** [comment]
That's an awesomely fast response time! Thanks for your work on Pachli. 👍
