### ISSUE TITLE
When composing a new toot, sometimes the app hangs for 10-20 seconds repeatedly

### ISSUE THREAD

**Issue by lgasp** [pachli/pachli-android#333]
**Describe the bug**
When composing a new toot, sometimes the app will hang for 10-20 seconds, then works for a few seconds and then hanging again and so on. Android would summon a popup  to propose me to kill the app because not responding again. If I choose to wait, the pop up will appear again after a few seconds. If I leave the compose window (wither by saving or not saving the draft, or by sending the toot), the app will work fine, but the android popups will continue appearing over and over until I decide to kill the app.

I would say that this behaviour happen 1 every 10 or 20 toot I compose, usually when they are kinda long

**To Reproduce**

1. click on the pencil icon on the lower right corner
2. Compose the message
3. The app hangs at a random time

**Expected behavior**
The compose window doesn't show the described bug

**Screenshots or video**
If applicable, please add screenshots or video to help explain your problem.

**Links**
If a particular post or posts demonstrate the problem please link to them here.

**Versions**

Pachli 2.0.0 
Android 13 y
server: happened when using accounts on both 3.x and 4.x mastodon. Seems unrelated to server, since it is on the compose window?

**Additional context**
*important* this happened also on Tusky (multiple versions), but I didn't open a new issue there because it doesn't happen frequently

**Affirmation**
"I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting."
i did this, hopefully well enough

**Comment by nikclayton** [comment]
What's the server? I've not seen this before, so I'm wondering if it's something that is server specific and might appear in the compose screen, like emoji selection?

**Comment by lgasp** [comment]
@nikclayton In sure it happens with mastodon.uno and pretty sure happened with mastodon.bida.im

I'm not able to reproduce it at will, but I will note down the context (toot being composed, server, something else?) when it happens again

**Comment by lgasp** [comment]
@nikclayton I don't see this issue anymore. Maybe it was related to something fixed on versions 2.1.0 and 2.2.0?

**Comment by nikclayton** [comment]
Maybe, I guess...? There wasn't anything in the Pachli code that changed specifically to address this, but maybe one of the Android library updates triggered something?

Anyway, good to hear that you're not having the problem any more, and thank you for coming back and updating the issue.

**Comment by lgasp** [comment]
So it still occasionally happens that the app hangs for some seconds when trying to retrieve hashtags or user accounts (guess waiting for server response)

What changed is that the system popup window proposing to close the app doesn't appear anymore, so now things are much better.

Thank you for the assistance!

**Comment by nikclayton** [comment]
Ah. So does this only happen if you have @-mentioned someone or started a hashtag and it's trying to auto complete in a menu?

**Comment by lgasp** [comment]
Yes, correct. When mentioning or hashtagging, occasionally the app hangs. I can still use keyboard, exit app etc, it's just the app itself that freezes for 10 s or so
