### ISSUE TITLE
Constant error message that filters cannot be loaded

### ISSUE THREAD

**Issue by charlie2alpha** [pachli/pachli-android#343]
I keep getting the error "Loading filters failed: Expected BEGIN_ARRAY but was STRING at line 1 column 2 path $" on the bottom of the screen. My instance doesn't support filters, I use GoToSocial which lacks many features compared to a full blown Mastodon instance but I don't have any other major issues except this annoying constant message. 

**To Reproduce**
1. Start the app
2. Error appears on the bottom of the screen

**Expected behavior**
No error should appear, filters are simply not supported.

This happens with Pachli current and latest stable. It doesn't happen with Tusky though, no error appears there, probably silently ignored which is what ideally Pachli should also do .

**Comment by nikclayton** [comment]
Thanks for the report. I'll try and get this resolved in the next minor release.

**Comment by martijndeb** [comment]
Sure, I run plantsand.coffee . Thanks for looking into it 👌

**Comment by SteveDinn** [comment]
I have exactly this issue. My go to social instance is gts.dinn.ca. just updated to the latest release this afternoon.

**Comment by nikclayton** [comment]
Note to self: The current approach in the code of sniffing version strings from the instance info API call can probably be improved. A better approach is probably:

1. Fetch `/.well-known/nodeinfo` and parse
2. Find the link with a supported schema (http://nodeinfo.diaspora.software/protocol.html)
3. Fetch the link and parse the JSON looking for the `software` block (`name` and `version`)

**Comment by charlie2alpha** [comment]
My instance name is fedi.charlie2alpha.org . Thanks for looking into it.

**Comment by gled-rs** [comment]
Small suggestion:
Maybe  you can consider adding a setting to not show those errors since it does not prevent the client from working ?
The popup is necessary to debug, I understand, but is not easy on the eyes when you have it every time you switch tabs .

Adding my thanks for looking into this too, this is the only issue that prevents me from migrating from Fedilab, and thank you for your work on this client, Pachli works extremely well apart from that small but super annoying issue, great job :)

Instance is ap.remote-shell.net if you need.

**Comment by nikclayton** [comment]
@charlie2alpha @martijndeb @SteveDinn @gled-rs Can you try Pachli Current (https://play.google.com/store/apps/details?id=app.pachli.current) tomorrow (it's building and uploading as I type this).

You'll know you've got the right version if this fix is mentioned in the "What's New" section on Google Play.

There should be two user-visible changes when logged in with your GoToSocial account.

1. You shouldn't see these errors any more
2. In "Account Preferences" you should still see the "Filters" option, but it should be disabled with a message noting that your server does not support filters.

Can you let me know if that works for you? Thanks.

**Comment by nikclayton** [comment]
It's on Google Play now.

**Comment by SteveDinn** [comment]
The latest update crashes on startup for me :(

**Comment by martijndeb** [comment]
I just sent a crash report too, I open the app and it immediately crashes.

**Comment by SteveDinn** [comment]
I tried clearing out the app's data. It lets me register an account and then immediately crashes

**Comment by nikclayton** [comment]
Thanks. The fix (https://github.com/pachli/pachli-android/pull/369) is building now. Should be on Google Play in a couple of hours.

You'd think this is the sort of thing that the Google Play app review process would catch, but apparently not...

**Comment by charlie2alpha** [comment]
Fixed version installed, message is gone and filters menu is disabled with a message reading they are unsupported. Many thanks!
