### ISSUE TITLE
Show announcement dates

### ISSUE THREAD

**Issue by nikclayton** [pachli/pachli-android#35]
**Is your feature request related to a problem? Please describe.**

According to https://universeodon.com/@siderea/110908421933987252 the app isn't showing date metadata associated with announcements.

**Describe the solution you'd like**

Show the date of each announcement in the Announcements screen.

**Comment by sanao1006** [comment]
Hello.
I would like to contribute to this wonderful project. May I try this task?

**Comment by nikclayton** [comment]
Yes, that would be great, thank you.

Please read through https://github.com/pachli/pachli-android/blob/main/docs/contributing/code.md if you haven't already.

A couple of things to think about:

- Please ensure that the display of the date/time of the announcement honours the user's "Use absolute time" preference (so it either appears as a date/time, or as something like "3 days ago" depending on their preference.

- There's an `all_day` property (https://docs.joinmastodon.org/entities/Announcement/#all_day), so if that's set the date should probably appear *without* any time (e..g, "Oct 10" or similar, not "Oct 10 00:00").

- As well as the `published_at` property there's an `updated_at` one as well, showing both to the user would be good.

**Comment by sanao1006** [comment]
- First, if "Use absolute time" is false, relative times such as "3 days ago" are displayed.
- Next, if "all_day" is true, the time is omitted (e.g., "Oct 10"), and if false, all time is displayed without omission (e.g., "Oct 10 00:00").
- If update_at and publish_at have different times, also display update_at (e.g., "Oct 10 (Updated: Oct 12)").

I consider the above approach. Please let me know if there are any problems.

**Comment by nikclayton** [comment]
Sounds good to me -- thanks.
