### ISSUE TITLE
Only usernames displayed on the timeline and not the actual display names

### ISSUE THREAD

**Issue by charlie2alpha** [pachli/pachli-android#371]
On the latest Pachli Current the user display names no longer appear, instead user's handle appear. Something seems to have regressed.

1. Open the app
2. Observe the names on the timeline, they are the user handles and not the display names. 

Observed in Pachli Current 2.1.1+a588c702

**Comment by nikclayton** [comment]
Thanks for the report, sorry about that. That'll be fixed in 2.2.
