### ISSUE TITLE
recent change introduced incompatibility with version format used in friendica

### ISSUE THREAD

**Issue by foss-** [pachli/pachli-android#372]
**Describe the bug**
A recent change introduced an incompatibility with the version format used in friendica. This is going on since ~1 week maybe. Version 2.1.1 does not complain about the friendica server version info format.

This is probably the change that introduced the conflict: https://github.com/pachli/pachli-android/pull/366

**To Reproduce**
1. open Pachli Current 2.1.1+a588c702 with friendica account.
 
**Expected behavior**
No error.

**Currrent behavior**
Error message at the bottom of screen: `Could not fetch server info: parsing server capabilities failed: could not parse "2024.03-dev-1547" as a version: Invalid version: 2024.03-dev-1547`.

**Screenshot**
<img src="https://github.com/pachli/pachli-android/assets/5708172/71f825a7-c3d0-4866-a2ce-59188cc91598" width="400">

**Versions**
Android 13

**Comment by nikclayton** [comment]
Thanks. I'll get that fixed before 2.2 is out (earliest Pachli Current release that will include the fix will probably happen on Tuesday 23rd Jan).
