### ISSUE TITLE
Hide self-boosts

### ISSUE THREAD

**Issue by nikclayton** [pachli/pachli-android#39]
Some Mastodon posters, otherwise reasonable people, have a profoundly annoying habit of boosting their own posts some time after they've posted them.

I've seen it once, I don't need to see the thing again.

For example, https://federate.social/@mattblaze/110198915334716075

Add an additional option to the "Filters > Tabs" preference to show these self-boosts (default: on)

**Comment by sanao1006** [comment]
@nikclayton 
Hi. I would like to work on this task!

**Comment by nikclayton** [comment]
That would be great, thanks.

One note about the implementation. I think it's OK if the preference is currently exposed to the user as switch ("Show self-boosts"), I could see a future where we want to allow the user to show a warning instead (the same way that filters currently work). So the actual preference value should be stored as an enum (`SHOW`, `HIDE`), so we can extend that to include `WARN` in the future.

And I think the preference option should be disabled if the user has disabled the existing "Show boosts" preference.

Does that make sense?

**Comment by sanao1006** [comment]
> Does that make sense?

Yes. Just my opinion, but it makes sense.

**Comment by sanao1006** [comment]
I have questions.

- This time use `switchPreference`.
- Is it correct that when the opportunity to use the `WARN` property comes up, the preference should be changed from `switchPreference` to `listPreference` at that time? (Because there are three properties `SHOW`, `HIDE` and `WARN`)

**Comment by nikclayton** [comment]
Yes, but...

... I've been looking at this in a bit more detail, in particular how `SwitchPreference` is implemented, and I think that makes the "Store an enum but show as a switch" approach that I suggested more complex than is necessary, given that there's infrastructure to migrate a given preference from one implementation to another when the user upgrades the app. That'll be easier to do if/when this supports more than just hiding self-boosts.

With that in mind I think a regular boolean preference will be fine.

**Comment by sanao1006** [comment]
Thank you for your research.
> With that in mind I think a regular boolean preference will be fine.

I got it!

**Comment by sanao1006** [comment]
I haven't done any serious coding yet, but I have installed the option (red line in the image). 

![image](https://github.com/pachli/pachli-android/assets/62137820/ad7bd506-dbfa-4283-8909-6cd663382ada)

Let me know if there is anything different from your image. If it's not a problem, I'll work on it.

**Comment by nikclayton** [comment]
Looks good. I would:

a. Move it under "Show boosts"
b. Add a short description underneath, like "Someone boosting their own post"
