### ISSUE TITLE
Home TL: Already viewed post keeps being treated as a new one on cold starts

### ISSUE THREAD

**Issue by tinsukE** [pachli/pachli-android#41]
**Describe the bug**
When viewing the Home TL, a post that was fetched on a previous session of the app keeps being treated as a new post on cold starts.

**To Reproduce**
1. Go to the Home tab
2. See a new post automatically load
3. Read the post
4. Optional - scroll down and up the TL
5. Optional - perform a pull to refresh
6. Kill and relaunch the app
7. The Home TL shows a loading animation and presents the (once new) post as a new one

**Expected behavior**
The Home TL is shown with the (once new) post treated as the rest of the posts on the TL

**Screenshots or video**
![old_toot](https://github.com/pachli/pachli-android/assets/1063155/71c68191-c74a-4d5f-9afe-c7f55ca9a9ce)

**Versions**
- Pachli: 1.0
- Server: 4.1.7
- Android 13

**Additional context**
I'm not sure it only happens on cold starts, but that's how I can repeatedly reproduce the issue whenever I see it happening.

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the detailedf report. This is the same underlying issue as #42 so I'm going to close this one in favour of that. There'll be a fix very shortly.
