### ISSUE TITLE
Home TL: Reading position isn't kept in between app launches

### ISSUE THREAD

**Issue by tinsukE** [pachli/pachli-android#42]
**Describe the bug**
When launching the app to the Home TL, once new posts are loaded in, the reading position isn't kept.

**To Reproduce**
1. Launch the app
2. On the Home tab, new content is loaded
3. The app overrides your position and takes you to the top of the new content

**Expected behavior**
New posts are loaded and inserted on top of your currently viewed posts, so you can keep scrolling up and reading posts in chronological order

**Screenshots or video**

https://github.com/pachli/pachli-android/assets/1063155/68d62138-fd5d-4949-aeca-9f83d6fa9939

https://github.com/pachli/pachli-android/assets/1063155/630b1e50-09b2-412d-ac4b-93d2f5c5bb26

**Versions**
- Pachli: 1.0
- Server: 4.1.7
- Android 13

**Additional context**
I'm not sure it only happens on cold starts, but that's how I managed to reproduce it.

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Fixed in #44
