### ISSUE TITLE
error when someone reacts to a post, breaking notification tab

### ISSUE THREAD

**Issue by Andre601** [pachli/pachli-android#461]
**Describe the bug**
When someone reacts to your post (in this case reaction from and to a glitch-soc instance) will Patchli not be able to handle, or ignore, said reaction, causing the notification tab to break.

**To Reproduce**

1. Use an account on an instance that supports reactions (i.e. glitch-soc)
2. Have someone react to a post of yours.

**Expected behavior**
Patchli should preferably support notifications of reactions.
Additionally should it ignore unknown notification types to not break the notification tab.

**Screenshots or video**
![SmartSelect_20240220-183203_Pachli Current](https://github.com/pachli/pachli-android/assets/11576465/fdf314cc-e356-4e39-a05a-97e98daa407a)

**Links**

**Versions**
Pachli Current 2.2.0+73c947ed

samsung SM-G960F 
Android-Version: 10 
SDK-Level: 29

**Additional context**

**Affirmation**
- [x] I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks. I thought that might occur. I know the cause, and should have a fix out for it today.

**Comment by nikclayton** [comment]
@Andre601 newest version of Pachli Current should fix this. Can you confirm it's working for you?
