### ISSUE TITLE
unexpected username format in latest pachli current @{name; handle@instance.io}

### ISSUE THREAD

**Issue by foss-** [pachli/pachli-android#518]
Android 13.1
Pachli Current 2.3.0+47624111

**Describe the bug**
Unexpected username format in latest pachli current @{name; handle@instance.io}

**To Reproduce**
1. Create a comment with a mention (probably affects all user handles in posts, not limited to comments, but this is where I found this first)
2. after posting comment, open comment and go to Edit comment

**Expected behavior**
Known `@handle@instance.io` format would be expected, instead seeing the more complex `@{name; handle@instance.io}` format.

**Comment by nikclayton** [comment]
This only seems to happen on messages sent from Friendica. I can't reproduce it on messages that I send between two accounts on mastodon.social, and if I send a message from a mastodon.social account to a pirati.ca account it doesn't reproduce.

The common theme there is that it's a mastodon.social account that can edit the status.

It does reproduce if I send a message from a pirati.ca account to a mastodon.social account (so it's a Friendica account that can edit the status).

It also reproduces in Pachli 2.3.0, so this isn't something that's come up in Pachli Current.

Checking the API response from pirati.ca shows that the API call `api/v1/statuses/{id}/source` is returning a source text that has the more complex format embedded in it (e.g., I see `@{Pachli; pachli@mastodon.social} Test from the web interface` in the API response).

An API response from a Mastodon server shows that as `@pachli@mastodon.social ...` as expected.

I don't see any recent changes to https://github.com/friendica/friendica/blame/develop/src/Object/Api/Mastodon/StatusSource.php that could have caused this on the Friendica side.

I'll report this on the Friendica bug tracker and see what they say.

**Comment by foss-** [comment]
Thanks for your patience with my reports and your following-ups in the friendica tracker. A few inconsistencies were already tackled that way. Since we have the friendica issue, closing my report here.

**Comment by foss-** [comment]
Just FYI: fixed in https://github.com/friendica/friendica/pull/13987
