### ISSUE TITLE
Crashing on GrapheneOS 14

### ISSUE THREAD

**Issue by gvansanden** [pachli/pachli-android#562]
**Describe the bug**
App started crashing constantly on GrapheneOS 14

**To Reproduce**
1. Browse the timeline for a couple of seconds to me nutes

**Expected behavior**
App crashes and closes

**Versions**
Pachli 2.3.0
Pleroma 2.7.2
Google Pixel 7
Android version: 14
SDK level: 34

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by gvansanden** [comment]
I just checked release dates and it is very possible this started with 2.3. 
I used pathcli for a while on this device without such issues.

**Comment by nikclayton** [comment]
Hi, thanks for the report, and sorry about the crashes.

Are you able to install Pachli Current, https://play.google.com/store/apps/details?id=app.pachli.current ?

If you are, that will help see if the problem is already fixed there. It also contains additional bug reporting features, allowing you to e-mail a crash report that will be very helpful for debugging.

What server is this happening with?

**Comment by gvansanden** [comment]
If you link me an apk I can upgrade. I installed from F-droid.

I use it with my own Pleroma server rebelbase.site, it used to work fine

22 Mar 2024 22:06:51 Nik Clayton ***@***.***>:

**Comment by nikclayton** [comment]
There's an apk in the "artifacts" section of https://github.com/pachli/pachli-android/actions/runs/8382516111

That should trigger a crash report dialog that will let you email details, including a log.

**Comment by gvansanden** [comment]
It is installed, will try it for a bit but it hasn't crashed on first use yet...

22 Mar 2024 23:27:50 Nik Clayton ***@***.***>:

**Comment by gvansanden** [comment]
It worked fine until now but the crashes started and won't stop. Report send

23 Mar 2024 08:56:17 Guy Van Sanden ***@***.***>:

**Comment by nikclayton** [comment]
Thanks, the report has shown the problem.

```
03-23 20:52:15.447 E/ACRA ( 8608): ACRA caught a JsonDataException for app.pachli.current
03-23 20:52:15.447 E/ACRA ( 8608): com.squareup.moshi.JsonDataException: Not an RFC 3339 date:
```

Your server is returning badly formatted data. I've found similar problem in Friendica (https://github.com/friendica/friendica/issues/13986) and I know Pleroma has some problems here (https://git.pleroma.social/dashboard/issues?sort=created_date&state=opened&author_username=nikclayton) but I've not seen this specific one before.

I've got a fix that should prevent the crash and show more data that can be passed to the Pleroma devs so they can fix this. Please can you try the APK linked to from https://github.com/pachli/pachli-android/pull/565#issuecomment-2016803095. That should show an error message with more details about where the problem is. If you can follow up here with the precise error message we'll be able to dig a bit further.

As I say, it won't crash, but you'll probably see that error constantly until the post that has the problem disappears from your home timeline.

**Comment by gvansanden** [comment]
Installed, will let you know.
Interesting though, my Pleroma server hasn't upgraded in a while and I used Patchli for weeks or longer without problems, this started showing up out of the blue.  It could be after the 2.3 release but not sure

24 Mar 2024 14:09:29 Nik Clayton ***@***.***>:

**Comment by nikclayton** [comment]
Thanks -- I just signed up for an account on rebelbase.site (account: pachli_test) to see if I can trigger the issue myself.

2.3.0 is stricter about how it processes the data it receives from a server. This has helped uncover a lot of server bugs, but it does introduce problems like these. I wrote more about this in the release post for 2.3.0, https://pachli.app/pachli/2024/02/28/2.3.0-release.html.

**Comment by gvansanden** [comment]
I approved your account

24 Mar 2024 14:34:44 Nik Clayton ***@***.***>:

**Comment by nikclayton** [comment]
Thanks, triggered it pretty quickly. It's similar to https://github.com/friendica/friendica/issues/13986.

I've reported this to the Pleroma devs at https://git.pleroma.social/pleroma/pleroma/-/issues/3261, and will work on a fix to prevent the crash.

**Comment by nikclayton** [comment]
@gvansanden Unrelated to the JSON issue there's something else odd about how rebelbase.site is configured.

When I set up the test account I didn't set an avatar.

This causes rebelbase.site to set the avatar to the URL "https://rebelbase.site/images/avi.png"

However, that is not an image -- if you fetch that URL it opens the site's login page. Not sure where in your configuration you'll need to look to fix that, but you should probably look in to it.

**Comment by gvansanden** [comment]
Thanks for following up on that. I will see if I can find why this happens...

24 Mar 2024 18:33:53 Nik Clayton ***@***.***>:

**Comment by nikclayton** [comment]
If you install the APK artifact from https://github.com/pachli/pachli-android/actions/runs/8411821101 you should see the problem is resolved. Can you confirm that it is for you? Thanks.

**Comment by gvansanden** [comment]
I have no more crashes with that version, thank you very much!

**Comment by nikclayton** [comment]
@gvansanden FYI, the version of Pachli Current you installed to test this *will not prompt you for updates*, so now you're done testing I recommend removing it and either using Pachli (regular) or switching to Pachli Current from Google Play, which will prompt you to keep up to date.

**Comment by gvansanden** [comment]
Thank you. I will remove it when I have a new ons from F-droid.

28 Mar 2024 23:56:53 Nik Clayton ***@***.***>:

**Comment by gvansanden** [comment]
Hi, I thought this was ok, but it seems that while Patchli does not crash and displays an error, it stops loading further posts. Meaning that if the top post has an invalid date, I can't further read the timeline. Can you take another look?

**Comment by nikclayton** [comment]
Can you send a link to the post that causes the problem?

**Comment by gvansanden** [comment]
It just gives the rfc date error and stops loading posts, but no link to which caused it...

30 Apr 2024 17:14:06 Nik Clayton ***@***.***>:

**Comment by nikclayton** [comment]
When that happens, in Pachli Current the top-right three-dot menu has a "Send error report" item. Can you use that, and it should include a log that points to the error.

**Comment by nikclayton** [comment]
Thanks, that was enough. I've just filed https://git.pleroma.social/pleroma/pleroma/-/issues/3268. Looks like I'll have to write a more lenient date parser as well.

Unfortunately I'll be on vacation in a few days for a couple of weeks, so I won't be able to get to this before then. Thanks for helping to troubleshoot this this far.

**Comment by gvansanden** [comment]
Enjoy the vacation and thank you for your responsiveness !

03 May 2024 17:35:36 Nik Clayton ***@***.***>:

**Comment by gvansanden** [comment]
Hi Nik, This issue is still there.  so to recap, Pachli gives an error on faulty posts but it also stops loading subsequent posts, so the timeline stops there.  If the first post is broken, There is no browsable timeline
