### ISSUE TITLE
Video / gif issue for lower bandwidth users

### ISSUE THREAD

**Issue by gregoryhammond** [pachli/pachli-android#598]
**Describe the bug**
If someone has lower bandwidth (or there is a bandwidth issue anywhere) and tries to play a video (or gif), it doesn't play, and you can scroll down to the next post where the player disappears.  There's no indication that it's being loaded.

**To Reproduce**
1. Go to any toot with a video, I used [@moxxi@mastodon.social as an example](https://mastodon.social/@moxxi/112219560443244540).
2. Click on the video to play it.
3. Try to wait for the video to play, in the meantime you may be able to scroll the rest of the post and when you move onto the next post, the video player disappears.

**Expected behavior**
Something to indicate that it's being loaded. And possibly the option to open with an external browser.

**Screenshots or video**
Video showing me trying this can be [seen on YouTube with no audio](https://youtube.com/shorts/paV2xbmMcXA).

**Links**
Particular post used as an example: [https://mastodon.social/@moxxi/112219560443244540](https://mastodon.social/@moxxi/112219560443244540)

**Versions**
Please include the version of Pachli and Android you are using, and the software version your server is using. Find this on the Pachli "About" screen.
Using Pachli version 2.4.0. Android version 13, SDK level 33. The server I'm on is using version 4.2.7.

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, and for including the video and example posts, that's very helpful. This'll be fixed in the next release.
