### ISSUE TITLE
Remove Tusky art

### ISSUE THREAD

**Issue by mileskrell** [pachli/pachli-android#681]
As part of establishing a visual identity distinct from Tusky, we should remove all Tusky-specific art from Pachli. A complete list can be found in [tuskyapp/artwork](https://github.com/tuskyapp/artwork). The art in that repo's `icons` folder was [explicitly made for Tusky](https://nocturne.works/tusky) and the art in the `art` folder was [also explicitly made for Tusky](https://github.com/mastodon/mastodon/issues/6060#issuecomment-413113719).

For now, we should be able to use [oops.png](https://github.com/mastodon/mastodon/blob/main/public/oops.png) instead. This is the image used on the [Mastodon web error page](https://mastodon.social/this_page_does_not_exist). Given its inclusion in the Mastodon repo, I understand it to be licensed under the GNU Affero GPL v3+, so as I understand it we can include a copy in Pachli.

Needless to say, I look forward to the day we have Pachli-specific art. But I think having user perception upon seeing Pachli's error pages go from "hey, that's the Tusky elephant" to "hey, that's the Mastodon elephant" is a step in the right direction.

**Comment by mileskrell** [comment]
I'm not currently a "collaborator" for this repo, so I can't assign myself this issue.
This is my notice that I'm starting work on a PR for this issue 🙂

**Comment by nikclayton** [comment]
I marked you as an assignee for this -- thanks.

Any Tusky icons or similar branding should be removed, for sure. Which ones remain?

For the errorphant I'd prefer to wait until there's alternative artwork for that. Using it in Pachli is in accordance with the license (CC-BY-SA) and it's credited in the licenses fragment.

We're about to have a membership (https://nivenly.org/blog/2024/04/26/pachli-decision/) which might help there, and I'd like us to be able to (a) work with an artist for new artwork (paying them, obviously), and (b) be able to give that artist a good brief for what that artwork should look like.

Maybe we can use this issue to brainstorm "b" a bit? As I said the other day the timing's not great as I'm about to leave for a couple of weeks, but I'll check in when I can.

**Comment by mileskrell** [comment]
Thanks for reminding me that the errorphant images are CC BY-SA. That choice of license *does* implicitly encourage non-Tusky projects to use those images. My thought process was something like "everyone will think of these images as the Tusky elephant and that will make Pachli look too similar to Tusky and that will make Pachli seem less of a legitimate independent project," but maybe I should have been thinking more along the lines of "it's the Mastodon elephant, and anyone is free to use or modify these images for any purpose, and it *just so happens* that Pachli and Tusky are the only two projects using them at the moment that I know of". I also realized that `oops.png` wouldn't be a good choice for the "empty collection" non-error anyway, so we'd still need another image. Let's keep the errorphant images for now.

Errorphant images aside, we do still have a Tusky banner at `assets/tusky_banner.xcf`.

Very exciting to hear about the Nivenly membership! Discussing the artwork is a good idea - I'll create a separate discussion for that so I can close this issue with a PR to remove that Tusky banner.

**Comment by mileskrell** [comment]
Created #683 with some art ideas!
