### ISSUE TITLE
error for firefish account when trying to fetch server info

### ISSUE THREAD

**Issue by foss-** [pachli/pachli-android#694]
**Describe the bug**
Error for firefish account when trying to fetch server info: `Could not fetch server info for procial.tchncs.de: fetching /api/v1/instance failed: timeout`

**To Reproduce**
1. create account on https://procial.tchncs.de
2. add account to pachli and browse timeline
3. after a while the error will show

**Expected behavior**
No trouble fetching server info. Maybe this report belongs in the Firefish tracker instead, if so, please let me know.

**Versions**
Pachli Current 2.5.1+23301213
Firefish 20240413

**Comment by nikclayton** [comment]
That was timing out for me earlier too, so I imagine procial.tchncs.de was down.

I'll look at making these error messages clearer when it's a networking issue that Pachli can't do anything about.

**Comment by foss-** [comment]
Instance has indeed been updated to latest release - closing.
