### ISSUE TITLE
Long-press on hyperlinks should bring up a dialog

### ISSUE THREAD

**Issue by cbiere** [pachli/pachli-android#695]
Tapping on a link opens the link in a browser immediately.
Long-pressing a link has no effect.

**Describe the solution you'd like**
 I would expect a menu with different actions or the share action where I can decide to copy the link to the clipboard or send it to a specific app. 

**Describe alternatives you've considered**
A workaround is to tap on the link so that is opened in the browser and then copy it or share it from there. However, for various reasons I don't always want to open the link right away.

**Comment by mileskrell** [comment]
You can select the text in posts, including links, but only after tapping that specific post to view it. Here's a vid:

https://github.com/pachli/pachli-android/assets/16272279/2a708f79-f040-464f-96f6-5b87444ca17b

But by contrast, you can tap links in posts to open them in your browser without having to first tap the post. I agree that it would make sense to align these behaviors: any place where you can tap a link to open it in your browser, you should also be able to also long-press links without having to first tap the post.

I just saw this same feature request (as a Mastodon post) from someone else recently, so this is definitely something we should improve. Thanks for filing the issue!

**Comment by mileskrell** [comment]
@cbiere, agreed - no rantiness taken 🙂

I think the experience when selecting links should be more like it is in other apps, meaning a dedicated context menu with at least an option to copy, but maybe also other options like share. I'm thinking of Firefox's behavior around links - you can select any text on a web page, but links get their own context menu on long-press. I haven't used fairemail but feel free to post a screenshot or recording if you feel it does an especially good job around this UI.

**Comment by mileskrell** [comment]
Given that there's a "Do not ask again" checkbox, I'm guessing that Fairemail has this dialog appear whenever you tap a link? I think most people would expect tapping a link to directly open it via the default browser, and I think that's probably the best behavior to go with. It would make sense to have a dedicated menu on long-press, but I agree that this Fairemail menu feels kind of excessive. On the other hand, the integration with ipinfo.io does sound cool. Maybe we start by adding an open/copy/share menu like Firefox and then we could think about what other options would be beneficial? I want to have useful options, I just don't want it to end up too cluttered.

**Comment by nikclayton** [comment]
This'll be implemented very shortly.

Long pressing a link (or a mention, or a hashtag) will show the normal Android "share sheet", with the link. From there you can copy it, or share it with any of the apps there.

In this screenshot I long-pressed on the link highlighted with the arrow:

<img src="https://github.com/user-attachments/assets/911c56f9-811d-4198-81c0-3e93472f4089" width="45%">
