### ISSUE TITLE
Pachli crashes when the "hidden domains" page fails to load

### ISSUE THREAD

**Issue by mileskrell** [pachli/pachli-android#696]
**Describe the bug**
Pachli crashes when navigating to Account preferences -> Hidden domains on an offline device.

**To Reproduce**
1. Start with an offline device
2. Open navigation drawer
3. Tap "Account preferences"
4. Tap "Hidden domains"
5. App crashes

**Expected behavior**
Pachli should show an error page instead of crashing.

**Screenshots or video**

This video shows me opening "Muted users" and "Blocked users" before "Hidden domains". Those first two pages demonstrate the behavior that I would like us to have for "Hidden domains", i.e. showing an error page rather than crashing.

https://github.com/pachli/pachli-android/assets/16272279/a5d26952-454d-4ad8-961a-e50f69e70d8d

**Versions**
Pachli Current 2.5.1+23301213
Android version: 14
Server version: 4.3.0-alpha.3+glitch

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by mileskrell** [comment]
Taking this one on - it seems like it should be straightforward to fix

**Comment by nikclayton** [comment]
Thanks. I'll be back to review in about a week and a half.
