### ISSUE TITLE
App closes constantly when trying to use context actions

### ISSUE THREAD

**Issue by Andre601** [pachli/pachli-android#722]
**Describe the bug**
When using context actions - in my case sharing or copying a link - is the app minimized/closed.

**To Reproduce**
1. Click the `...` of a post
2. Select an option. I.e. copy link
3. See app closing/minimizing

**Expected behavior**
App shouldn't close.

**Screenshots or video**
https://github.com/pachli/pachli-android/assets/11576465/9183da1a-44c8-46ec-bb8f-dc02a83b25b0

**Links**
Encountered this first time on this post:
https://mastodon.tinyfox.dev/@hourlyfops/112535117030943410

**Versions**
Pachli 2.5.1

Device:

samsung SM-G960F 
Android-Version: 10 
SDK-Level: 29

Account:

@andre_601@blobfox.coffee 
Version: 4.3.0-alpha.3+glitch+blobfox

**Additional context**

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, and sorry about that.

This sounds like https://github.com/pachli/pachli-android/issues/700, which is fixed in Pachli Current. I'm preparing to release 2.5.2 today which also includes the fix.

Can you try with Pachli Current, and/or 2.5.2 (when it's released) and see if that fixes the problem for you?

**Comment by nikclayton** [comment]
@Andre601 2.5.2 is in wide release now -- has this resolved the problem for you?

**Comment by Andre601** [comment]
I have to check once f-droid updates its indexes.
Still has 2.5.1 as latest.

**Comment by Andre601** [comment]
Updated and seems to be fixed.
