### ISSUE TITLE
Add more space between image descriptions

### ISSUE THREAD

**Issue by jumase** [pachli/pachli-android#751]
**Is your feature request related to a problem? Please describe.**
I use Pachli with "Download media previews" disabled (to save bandwidth and improve navigation on unstable internet connections) and, when viewing posts with more than one image, it's quite difficult to notice where one description ends and the next one begins.

**Describe the solution you'd like**
I propose adding more space between file descriptions, the same amount as there is just before/above the first file description.

**Describe alternatives you've considered**
There could be lines or something else between files descriptions, but I think that increasing space is neater. The mini icon also gives you an indication to where an image description would end and begin, because it's in the middle. But, for long descriptions, difficulty increases.

**Additional context**
The first screenshot is the current state (Pachli 2.5.2). In this resolution line space is 15 pixels and space between descriptions is 18 px. You can hardly distinguish where the second image description begins, especially when there are several capital letters, full stops missing or no capitalization at all. Notice that space before/above first description is 30 px, i.e. double line space.

![Current](https://github.com/pachli/pachli-android/assets/96543724/5dd52a41-1d2c-496f-8f40-a3ace6a7c9ea)

The second "screenshot" is an edition I made to show you how it would be displayed if space between descriptions were 30 px —I moved second alt text 12 px down.

![Edit](https://github.com/pachli/pachli-android/assets/96543724/7b674602-f94c-47ea-930b-22059ce508c8)

**Comment by nikclayton** [comment]
Thanks for the suggestion. This will be fixed in the next release.

Two changes.

1. More spacing between the media descriptions.
2. The icons have been moved to the first row of description, as a clearer indicator of where each description starts.

![Screenshot_20240624-223532.png](https://github.com/pachli/pachli-android/assets/773100/a9c9d900-7dc8-4eae-a3f2-94565b705a2c)

Let me know if you've got any feedback on the new UX.
