### ISSUE TITLE
status bar has light blue background

### ISSUE THREAD

**Issue by foss-** [pachli/pachli-android#79]
**Describe the bug**
On all accounts the status bar uses the light blue highlight color. Not sure why that would be. In dark mode it does not work well since it is a very bright color which is continuously shown at the top of screen. The low contrast makes reading the status bar hard.

**To Reproduce**
open any timeline on any account and look at status bar.

**Expected behavior**
The status bar background should probably be identical to the background color used for posts.

**Screenshots or video**
<img src="https://github.com/pachli/pachli-android/assets/5708172/a3ac2831-e389-4113-9274-1b48dbbacbd3" width="300">

**Versions**
Android 13.1 (ArrowOS)
Pachli 1.1

**Comment by nikclayton** [comment]
Yep, that's a bug. There are some related ones as well (e.g., the Bookmarks and Trending screens have different colours for the action bar, Bookmarks is correct). These will be fixed in 1.2.
