### ISSUE TITLE
Character limit calculated wrong on CW replies

### ISSUE THREAD

**Issue by BDGreyson** [pachli/pachli-android#815]
**Describe the bug**
When REPLYING to Toots with content warnings the characters taken up by the warning are not counted towards the character limit, thus causing errors when posting.

**To Reproduce**
1. Create a text that has exactly as many characters as the server limit
2. Create a post with a content warning
3. Paste the exact-limit text in a reply to the post where the reply automatically copies the CW of the original Toot
4. Sending fails because full-limit text + the original CW go over the server limit

**Expected behavior**
As soon as the reply is started, the characters in the CW that the reply automatically adds from the original post needs to be substracted from the "remaining characters" count

**Versions**
Pachli 2.6.0 (F-Droid)
Google Pixel 7
Android 14
SDK 34

Mastodon Server version: 4.2.10

**Affirmation**
X I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, and sorry about that. I've found and fixed the problem, it'll be included in the Pachli release at the end of this month.
