### ISSUE TITLE
@usernames should not determine bidi direction

### ISSUE THREAD

**Issue by NeatNit** [pachli/pachli-android#870]
**Describe the bug**
For users in Hebrew, Arabic or Persian (I think) which are written right to left, the @mentions at the start of a reply cause the entire first paragraph to be rendered left to right. This causes it to be less readable. 

If this were HTML, I'd suggest you wrap any mention in a bdi tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi (or use CSS which can also do that).

**To Reproduce**
1. Reply to anything
2. Include the default mention, and write in a RTL language. Finish with a punctuation mark. For example: 
  @whoever שיהיה לך יום טוב.
4. Post and look at the result

**Expected behavior**
The paragraph should be rendered in RTL, aligned right, and the punctuation mark should be on the left at the end of the text.

**Screenshots or video**
![Screenshot_20240806_044530_Pachli](https://github.com/user-attachments/assets/9f007f12-1a2e-4300-a8a7-09e07f1d1d17)

**Links**
https://fosstodon.org/@neatnit/112912082714265949

**Versions**
Pachli 2.7.0, Android 14, OneUI 6.1, Samsung Galaxy S22+.

**Affirmation**
I did not check for other issues, sorry. Feels like the kind of issue that would be resolved soon after it's brought up.

**Comment by nikclayton** [comment]
Would you be able to do a quick mockup showing what that screenshot should look like if things are working correctly? That'll help me verify any changes are working correctly.

Note to self: https://developer.android.com/reference/android/text/BidiFormatter

**Comment by NeatNit** [comment]
No need for a mockup, the website does it fine:

![Screenshot_20240807_084321_Fennec](https://github.com/user-attachments/assets/a10ebd4d-a8c4-43c7-bfe4-f91b4523db2b)

**Comment by NeatNit** [comment]
Oh, I just noticed that **the behavior is already correct in the main timeline** ([or my timeline with replies](https://fosstodon.org/@neatnit/with_replies)), but not when entering the post or its parent.

**Comment by NeatNit** [comment]
Though, the @ symbol should appear to the left of a username in either case.

Effectively, it seems like it's doing this: `@<bdi>username</bdi> {{rest of the message}}`

When it should be doing this: `<bdi>@username</bdi> {{rest of the message}}`

And of course, this should apply to each username mention individually, even in the middle of a post.
