### ISSUE TITLE
timeout when fetching posts

### ISSUE THREAD

**Issue by foss-** [pachli/pachli-android#88]
Pachli 1.1
Android 13.1

**Describe the bug**
Using Pachli with two friendica accounts and while fetching posts mostly works with squeet.me, pirati.ca is causing a lot of headache. In all attempts to fetch posts exept for one this resulted in `A network error occurred: timeout ` exactely 30 seconds after initiating the fetch.

**To Reproduce**
fetch new posts with friendica account on pirati.ca instance.

**Expected behavior**
Posts should be fetched.

**Additional info**
After talking to the admin of both instances I learned, that pirati.ca has a tendency to be not as responsive as squeet.me. Despite having a lot less users, it is on much weaker hardware.

Another data point: been using pirati.ca account in tusky, fedilab and other clients without timeouts. So not sure why it is triggering so many timeouts with Pachli.

**Comment by nikclayton** [comment]
The error being reported after 30 seconds is consistent with the network timeout in Pachli.

When that happens there's not much that the app can do. It could retry automatically, but if there is a network issue, or the server is not responding that doesn't help the situation, and may make the issue worse (consider what would happen if every Mastodon client automatically continually retried if the server reported an error -- servers with intermittent network issues would be under a regular barrage of repeat requests from badly behaving clients).

> Another data point: been using pirati.ca account in tusky, fedilab and other clients without timeouts. So not sure why it is triggering so many timeouts with Pachli.

I think that's a red herring. The low-level networking code in Tusky and Pachli is currently identical.

I'm happy to look in to this further, but for that I think I'll need an account on pirati.ca. It's not clear from that site how to register for an account -- do you know how?

**Comment by foss-** [comment]
You got a DM in your mastodon

**Comment by foss-** [comment]
Unsure if this is the same issue or a separate problem, but since the 1.2.2 update seeing the following error:

```
A network error occurred:
java.lang.RuntimeException:
java.lang.RuntimeException:
java.security.KeyStoreException: BKS not found
```

**Comment by foss-** [comment]
Cross-linking a potential fix: https://github.com/friendica/friendica/pull/13557

**Comment by foss-** [comment]
https://github.com/friendica/friendica/pull/13557 is now running on pirati.ca and the problem is indeed resolved. Closing 🚀
