### ISSUE TITLE
question about language is not good

### ISSUE THREAD

**Issue by muellerto** [pachli/pachli-android#893]
**Describe the bug**
I get the new question about the language of my post several times a day. In this incidence I see this as a bug. 

**To Reproduce**
That's complicated. I haven't found out until now why this question comes, by what it is triggered. Some posts cause the question, others do not. This lack of transparency is part of the problem - the user doesn't know what this question is all about. He uses a language in his posts and then, in the moment right before sending, this thing asks if the language should be switched. In my use case this question is **always misplaced**, I answer No in every single case, this is really for nothing.

**Expected behavior**
I want to post what I want and not what any damned question wants to be changed. I formulate my posts very carefully and I want that they are sent exactly like this, always, with no exception.

I suggest to make an option: "[x] ask for language before sending". I would switch this off once for all immediately.

If there are other options this question is depending on it should be made more transparent so that the user can change them to avoid this annoying question.

**Versions**
2.7.1

**Additional context**
I changed already the languages from Pachli and from the posts to German, both have been Standard before. This didn't help at all, I get the question still again and again.

**Comment by nikclayton** [comment]
Hi, thanks for the feedback, sorry this is frustrating.

## Samples

Can you send a link to any of the posts you've written where this is happening? This'll help me better understand the cause of the problem.

## What's happening

When you hit the button to send the message Pachli tries to identify the language your post is written in.

Multiple possible languages might be identified. If your chosen language is any of these then you're not supposed to be prompted.

Each identified language has a confidence associated with it -- how likely it is this is the actual language. It's a percentage.

If the confidence for a language is less than 60% it's ignored.

Only then will Pachli suggest that the language might be wrong.

In other words, when Pachli tried to identify the language in your post and compare it the language you've set.

- None of the identified languages match the language you chose
- The language identifier is 60+% confident in the identity of the most likely language

That's supposed to prevent the sort of false positives that you're seeing. So some links to examples so I can try and reproduce the problem would be very helpful.

## Ignore this

When I introduced the feature I considered adding a third "Don't prompt me again" option to the dialog, which would set a preference. I decided against that at the time to try and avoid overloading the user with decisions and preferences. This is the sort of thing that should "just work".

It's possible that's not the correct solution, so with some of those links I can take a look, and see if it makes sense to revisit that.

To set some expectations -- the next Pachli release will be next week, so I don't think I'll likely be able to get any changes in to that release, but it should be possible in the one at the end of September. Links will definitely make that easier.

Thanks again for the report.

**Comment by muellerto** [comment]
I understand all that. But my posts don't have "a language". It's a technical use case. I use a private Mastodon feed to bring inputs from several front ends into a clear and definitive order (by time). Then a robot comes from time to time and reads the feed to fill a database with these values. My inputs look like this (each line a post):

`m`
`2n`
`5.6 m 8n`
`30t ; this is comment`
`7.8* p e n`
`2024-08-16-05:33:00 7.8 m 3n`

My entire feed looks like this.

The suggested language is always Arabic, don't know why. I also never checked what then happens when I use Arabic.

**Comment by Morethanevil** [comment]
This question is going on my nerves too. I set the language to german, but if I use a neocat emoji or two it is more english than german from the text perspective. Everytime I get asked about the language. That is annoying 😔

Pachli is such a good app, please let us turn this off

![Screenshot_2024-10-11-07-16-01-64_392a520eac50dcd4b92a77d716925e7b](https://github.com/user-attachments/assets/8921f9aa-5004-4201-944d-ac5f029e564d)

**Comment by muellerto** [comment]
Indeed that's the reason why I'm currently back on Subway Tooter as long as Pachli shows this behavior. ST sends what I want without any question and does also an automatic refresh after sending.

**Comment by nikclayton** [comment]
Thanks all for the feedback.

The next Pachli Current (later today), will add a "Don't ask me again" option to the dialog. This is also shown as a new preference in the app's preferences, so if you accidentally tap that you can reset it.

This'll be in the Pachli 2.8.3 release at the end of the month.
