### ISSUE TITLE
3 issue with pixelfed.uno

### ISSUE THREAD

**Issue by lichingyun** [pachli/pachli-android#913]
**Describe the bug**
Hello, I post here 3 screenshot from my mobile phone in which I login to pixelfed.uno and find 3 problems

**To Reproduce**
1.Login to pixelfed.uno
2. When I login appear an error message at the bottom of the screen
3. Also the notification area and the directl messages area cannot show anything 

**Versions**
I am using Pachli 2.7.1 from F-droid, my mobile is a Oneplus Nord 2 with original Android 13. I was logged to pixelfed.uno
![Screenshot_2024-08-29-15-08-27-06_392a520eac50dcd4b92a77d716925e7b](https://github.com/user-attachments/assets/64cdfcc4-2a92-49bd-af9f-b687e4eb1e9f)
![Screenshot_2024-08-29-15-13-03-66_392a520eac50dcd4b92a77d716925e7b](https://github.com/user-attachments/assets/6d8930e6-bc28-4669-9f16-093919b5fabe)
![Screenshot_2024-08-29-15-12-58-02_392a520eac50dcd4b92a77d716925e7b](https://github.com/user-attachments/assets/9ea20f6f-6c52-4018-ac5c-c7f6f22fb1df)

**Comment by nikclayton** [comment]
Pixelfed is not compatible with the Mastodon API, so is not supported at the moment.

https://github.com/pixelfed/pixelfed/issues?q=is%3Aissue+is%3Aopen+api+label%3A%22%F0%9F%94%83+API%22 is the currently open list of Pixelfed API issues. Unfortunately I don't know when they will be fixed, or how they are prioritised.
