### ISSUE TITLE
Save attachments to individual folders

### ISSUE THREAD

**Issue by bee8bit** [pachli/pachli-android#938]
**Is your feature request related to a problem? Please describe.**
I save a lot of images from vatious toots. This quickly clutters my downloads folder which I have tp clean up regularly by sorting files manually.

**Describe the solution you'd like**
I would like to enable an option that attachments are automatically saved in a subfolder that is named according to the sender's handle.

**Describe alternatives you've considered**
An alternative could be that pachli opens a path selector that allows me to quickly pick a subfolder (always starting from the default location, not from the most recently used one), perhaps only when I long-press the same button.
But this path pocket would need to be quick so it isn't annoying. And perhaps allow me to create new folders about the way.

**Comment by nikclayton** [comment]
So a preference titled something like "Download location", that had the following two options:

```
( ) Downloads folder
( ) Per-account folders, in Downloads folder
```

would suffice?

**Comment by bee8bit** [comment]
Yes, that would be perfectly fine for me.
