### ISSUE TITLE
Option to choose tab-tap behaviour.

### ISSUE THREAD

**Issue by nikclayton** [pachli/pachli-android#939]
Some people want tab-tap to act like "Load newest". This is dangerous behaviour to have as default (the user might be taken very far from their chosen position), but it seems reasonable to add as an option.

So a general preference, something like "Tab-tap behaviour" and two options:

```
(x) Jump up one page
( ) Jump to newest posts
```

See https://troet.cafe/@andreas_heitmann/113157476673289558

**Comment by nichu42** [comment]
Oh yes, please!

**Comment by nichu42** [comment]
Just wanted to let you know that the lab feature works perfectly! I wouldn't want to miss it.
