### ISSUE TITLE
Poll not saved when schedule post

### ISSUE THREAD

**Issue by gregoryhammond** [pachli/pachli-android#991]
**Describe the bug**
After scheduling a post, then going to edit it, the poll (that was in the post when first scheduled) isn't there.

**To Reproduce**
1. Write a post that includes a poll.
2. Schedule it (doesn't matter date or time).
3. Go into the scheduled post list, find your scheduled post, then edit it.
4. See that the poll you previously wrote, no longer exists.

**Expected behavior**
Poll that was written before post was scheduled, still exists when editing it again.

**Versions**
Pachli version: 2.8.2
Android version: 14
Software version server is using: 4.4.0-alpha.1

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Thanks for the report, sorry about that. Fix is incoming, and will be in the next Pachli release at the end of the month.
